version: '3'

services:

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - backend_db_volume:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  backend_db_volume: